# Generated by Django 3.1.2 on 2020-10-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('Join_Date', models.DateTimeField(auto_now=True)),
                ('User_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Email', models.CharField(max_length=100)),
                ('User_Mobile', models.CharField(max_length=15)),
                ('User_Gender', models.CharField(max_length=10)),
                ('User_Age', models.CharField(max_length=5)),
                ('User_City', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Deactive', max_length=10)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
