# Generated by Django 3.1.1 on 2020-10-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='User_Password',
            field=models.CharField(default='Not Set', max_length=20),
        ),
    ]
