# Generated by Django 3.1.2 on 2020-11-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userpicturedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keywords', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitemap', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Sitemap',
            },
        ),
    ]
